name: Changelog

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Generate changelog
      env:
        GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
      run: npx changelog
