name: Changelog
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          $GITHUB_AUTH:${{ secrets.GITHUB_TOKEN }} npx lerna-changelog --version
