name: Label
on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize]

  jobs:
    uses: jesusvasquez333/verify-pr-label-action@v1.3.1
    with:
      github-token: '${{ secrets.GITHUB_TOKEN }}'
      pull-request-number: '${{ github.event.pull_request.number }}'
      valid-labels: 'breaking, enhancement, bug, documentation, internal'

#name: Label
#on:
#  pull_request:
#    types: [labeled, unlabeled, opened, edited, synchronize]
#jobs:
#  required:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: yogevbd/enforce-label-action@2.2.1
#      with:
#        REQUIRED_LABELS_ANY: "breaking, enhancement, bug, documentation, internal"
#        REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['breaking','enhancement','bug','documentation','internal','skip-changelog']"
#        #BANNED_LABELS: "banned"

#name: Label
#on:
#  pull_request:
#    types: [opened, labeled, unlabeled, synchronize]
#jobs:
#  required:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: mheap/github-action-required-labels@v1
#        with:
#          mode: exactly
#          count: 1
#          labels: "breaking, enhancement, bug, documentation, internal"
#
#name: Release Drafter
#
#on:
#  push:
#    # branches to consider in the event; optional, defaults to all
#    branches:
#      - main
#      - alpha
#
#jobs:
#  update_release_draft:
#    runs-on: ubuntu-latest
#    steps:
#      # Drafts your next Release notes as Pull Requests are merged into "master"
#      - uses: release-drafter/release-drafter@v5.12.1
#        # with:
#          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
#          # config-name: my-config.yml
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
